// Copies pako's deflate-only browser build (and its license) out of
// node_modules and into the project root, where the manifest's
// content_scripts load `pako_deflate.min.js` directly (no bundler — see
// CLAUDE.md). Neither output file is committed: both are regenerated by
// `npm install`/`npm run build`, not checked into git.

import { copyFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

function copy(sourcePath, destinationName) {
  const destination = join(projectRoot, destinationName);
  copyFileSync(sourcePath, destination);
  console.log(`Copied ${sourcePath} -> ${destination}`);
}

copy(require.resolve('pako/dist/pako_deflate.min.js'), 'pako_deflate.min.js');
copy(join(dirname(require.resolve('pako/package.json')), 'LICENSE'), 'PAKO_LICENSE');
